fix + add exit code check
Signed-off-by: Sarah Funkhouser <147884153+golanglemonade@users.noreply.github.com>

diff --git a/.buildkite/pipeline.yaml b/.buildkite/pipeline.yaml
--- a/.buildkite/pipeline.yaml
+++ b/.buildkite/pipeline.yaml
@@ -25,8 +25,15 @@ steps:
             - "GITHUB_TOKEN"
     command: |
       #!/bin/sh
+      set -e
       echo "--- running go generate"
       task generate
+      EXIT_CODE=$?
+
+      if [ $EXIT_CODE -ne 0 ]; then
+        echo "task generate failed with exit code $EXIT_CODE"
+        exit $EXIT_CODE
+      fi
 
       echo "--- configuring git user"
       git config user.name "theopenlane-bender"
