fix: pr on main to ensure tests run, add logo to standard
Signed-off-by: Sarah Funkhouser <147884153+golanglemonade@users.noreply.github.com>

diff --git a/.buildkite/pipeline.yaml b/.buildkite/pipeline.yaml
--- a/.buildkite/pipeline.yaml
+++ b/.buildkite/pipeline.yaml
@@ -3,19 +3,21 @@ env:
   GOMODCACHE: $HOME/.cache/go/pkg/mod
   GOLANGCI_LINT_CACHE: $HOME/.cache/golangci-lint
 
+secrets:
+  - GITHUB_TOKEN
+  - APOLLO_KEY
+  - GITHUB_SSH_PRIVATE_KEY
+
 steps:
-  - label: ":graphql: generate"
+  - label: ":graphql: generate branch changes"
     key: "generate"
+    if: build.branch != "main"
     agents:
       queue: $LARGE_RUNNER_QUEUE
       size: $RUNNER_LARGE
       location: "NYC"
     cancel_on_build_failing: true
     plugins:
-      - cluster-secrets#v1.0.0:
-          variables:
-            APOLLO_KEY: APOLLO_KEY
-            GITHUB_TOKEN: GITHUB_TOKEN
       - docker#v5.13.0:
           image: "ghcr.io/theopenlane/build-image:latest"
           always_pull: true
@@ -24,13 +26,15 @@ steps:
             - "APOLLO_KEY"
             - "GITHUB_TOKEN"
     command: |
-      #!/bin/sh
+      #!/bin/bash
       set -e
+      set -o pipefail
+
       echo "--- running go generate"
       task generate
       EXIT_CODE=$?
 
-      if [ $EXIT_CODE -ne 0 ]; then
+      if [ "$EXIT_CODE" -ne 0 ]; then
         echo "task generate failed with exit code $EXIT_CODE"
         exit $EXIT_CODE
       fi
@@ -56,6 +60,63 @@ steps:
       echo "--- pushing to origin ${BUILDKITE_BRANCH}"
       git push "https://x-access-token:$${GITHUB_TOKEN}@github.com/theopenlane/go-client.git" "HEAD:${BUILDKITE_BRANCH}"
 
+  - label: ":graphql: generate and pr changes"
+    key: "generate-main"
+    if: build.branch == "main"
+    agents:
+      queue: $LARGE_RUNNER_QUEUE
+      size: $RUNNER_LARGE
+      location: "NYC"
+    cancel_on_build_failing: true
+    plugins:
+      - docker#v5.13.0:
+          image: "ghcr.io/theopenlane/build-image:latest"
+          always_pull: true
+          propagate-environment: true
+          environment:
+            - "APOLLO_KEY"
+            - "GITHUB_TOKEN"
+            - "BUILDKITE_AGENT_ACCESS_TOKEN"
+    command: |
+      #!/bin/bash
+      set -e
+      set -o pipefail
+
+      echo "--- running go generate"
+      task generate
+      EXIT_CODE=$?
+
+      if [ "$EXIT_CODE" -ne 0 ]; then
+        echo "task generate failed with exit code $EXIT_CODE"
+        exit $EXIT_CODE
+      fi
+
+      echo "--- configuring git user"
+      git config user.name "theopenlane-bender"
+      git config user.email "theopenlane-bender@users.noreply.github.com"
+
+      echo "--- checking for changes"
+      if git diff --quiet; then
+        echo "No changes from go generate; nothing to commit."
+        exit 0
+      fi
+
+      echo "--- committing changes"
+      branchName="chore/go-generate-$(date +%s)"
+      git status
+      git checkout -b "$$branchName"
+      git add -u
+
+      # commit changes
+      git commit -m "chore: run go generate"
+
+      echo "--- pushing to origin $$branchName"
+      git push "https://x-access-token:$${GITHUB_TOKEN}@github.com/theopenlane/go-client.git" "HEAD:$$branchName"
+
+      echo "Changes found, creating pull request..."
+      export branchName
+      sed "s|\[branchName\]|$$branchName|g" .buildkite/steps/pr.yaml | buildkite-agent pipeline upload
+
   - label: ":golangci-lint: lint :lint-roller:"
     if_changed:
       - "**.go"
@@ -66,9 +127,6 @@ steps:
     cancel_on_build_failing: true
     key: "lint"
     plugins:
-      - cluster-secrets#v1.0.0:
-          variables:
-            GITHUB_SSH_PRIVATE_KEY: GITHUB_SSH_PRIVATE_KEY
       - docker#v5.13.0:
           image: "ghcr.io/theopenlane/build-image:latest"
           command: ["task", "go:lint:ci"]
@@ -86,9 +144,6 @@ steps:
       - "**.go"
       - "go.mod"
     plugins:
-      - cluster-secrets#v1.0.0:
-          variables:
-            GITHUB_SSH_PRIVATE_KEY: GITHUB_SSH_PRIVATE_KEY
       - docker#v5.13.0:
           image: "ghcr.io/theopenlane/build-image:latest"
           always-pull: true
